version: 2

project_name: paws

before:
  hooks:
    - go mod tidy

builds:
  - id: paws
    main: .
    binary: paws
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - '-s -w -X main.version={{.Version}}'

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

release:
  github:
    owner: lzecca78
    name: awsd
  draft: false
  prerelease: auto

changelog:
  use: file
