version: 2

project_name: paws

before:
  hooks:
    - go mod tidy

builds:
  - id: paws
    main: .
    binary: paws
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - '-s -w -X main.version={{.Version}}'

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

release:
  github:
    owner: lzecca78
    name: paws
  draft: false
  prerelease: auto

changelog:
  use: file

brews:
  - name: paws
    github:
      owner: lzecca78
      name: homebrew-paws
    folder: Formula
    homepage: 'https://gihub.com/lzecca78/paws'
    description: 'paws is a CLI tool for AWS profile management and Pulumi login and stack selection.'
    conflicts:
      - paws
    test: |
      system "#{bin}/paws"
    install: |
      bin.install 'paws'
