version: 2

project_name: paws

before:
  hooks:
    - go mod tidy

builds:
  - id: paws
    main: .
    binary: paws
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - '-s -w -X main.version={{.Version}}'

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - src: scripts/_paws
        dst: _paws
        info:
          mode: 0755

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

release:
  github:
    owner: lzecca78
    name: paws
  draft: false
  prerelease: auto

changelog:
  use: file

homebrew_casks:
  - name: paws
    binary: paws
    commit_author:
      name: lzecca78
      email: l.zecca78@gmail.com
    commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"
    repository:
        owner: lzecca78
        name: homebrew-paws
